export const FETCH_USER_INTERACTIONS = 'FETCH_USER_INTERACTIONS';
export const UPSERT_USER_INTERACTION = 'UPSERT_USER_INTERACTION';
export const EXECUTE_COMMAND = 'EXECUTE_COMMAND';
export const DISABLE_INTERACTION_MODE = 'DISABLE_INTERACTION_MODE';