export const LOADING_USER_INTERACTIONS = 'LOADING_USER_INTERACTIONS';
export const ASYNC_LOADING = 'ASYNC_LOADING';
export const USER_INTERACTIONS = 'USER_INTERACTIONS';
export const FIND_USER_INTERACTION_BY_ID = 'FIND_USER_INTERACTION_BY_ID';
