export const SET_ASYNC_LOADING = 'SET_ASYNC_LOADING';
export const SET_LOADING_USER_INTERACTIONS = 'SET_LOADING_USER_INTERACTIONS';
export const SET_USER_INTERACTIONS = 'SET_USER_INTERACTIONS';
export const UPSERT_USER_INTERACTION = 'UPSERT_USER_INTERACTION';
