export const SUBSCRIBE_PIPELINE_CHANGED = 'SUBSCRIBE_PIPELINE_CHANGED';
export const SUBSCRIBE_PIPELINE_PARSED_LINES = 'SUBSCRIBE_PIPELINE_PARSED_LINES';
export const SUBSCRIBE_PIPELINE_EXECUTE_COMMAND = 'SUBSCRIBE_PIPELINE_EXECUTE_COMMAND';
export const SUBSCRIBE_PIPELINE_ALL = 'SUBSCRIBE_PIPELINE_ALL';
export const WEBSOCKET_CONNECT = 'WEBSOCKET_CONNECT';
export const FETCH_APP_VERSION = 'FETCH_APP_VERSION';
