export const IS_MOBILE_VIEW = 'IS_MOBILE_VIEW';
export const IS_XS_ONLY = 'IS_XS_ONLY';
export const IS_SM_ONLY = 'IS_SM_ONLY';
export const SHOW_VERTICAL_MENU = 'SHOW_VERTICAL_MENU';
export const SNACK_MESSAGE = 'SNACK_MESSAGE';
export const SNACK_MESSAGE_COLOR = 'SNACK_MESSAGE_COLOR';
