export const SET_SNACK_MESSAGE = 'SET_SNACK_MESSAGE';
export const SET_SHOW_VERTICAL_MENU = 'SET_SHOW_VERTICAL_MENU';
export const SET_APP_VERSION = 'SET_APP_VERSION';
export const SET_APP_LAST_UPDATED = 'SET_APP_LAST_UPDATED';
export const TOGGLE_SHOW_VERTICAL_MENU = 'TOGGLE_SHOW_VERTICAL_MENU';
