export const SET_LOADING = 'SET_LOADING';
export const SET_PIPELINE_LOADING = 'SET_PIPELINE_LOADING';
export const PIPELINE_CHANGE = 'PIPELINE_CHANGE';
export const PIPELINE_CHANGE_ATTRIBUTE = 'PIPELINE_CHANGE_ATTRIBUTE';
export const PIPELINES_SET_FROM_ARRAY = 'PIPELINES_SET_FROM_ARRAY';
export const REMOVE = 'REMOVE';
export const SET_NEW_PARSE_ROWS_COUNT = 'SET_NEW_PARSE_ROWS_COUNT';
