export const TASK_ANALYZED_COMMANDS = 'TASK_ANALYZED_COMMANDS';
export const SHOW_ONLY_WITH_ERROR = 'SHOW_ONLY_WITH_ERROR';
export const LOOP_DISPLAY_INDEXES_BY_UUID = 'LOOP_DISPLAY_INDEXES_BY_UUID';
