export const INITIALIZE_DEFAULT_LOOP_DISPLAY_INDEX = 'INITIALIZE_DEFAULT_LOOP_DISPLAY_INDEX';
export const SET_LOOP_DISPLAY_INDEX = 'SET_LOOP_DISPLAY_INDEX';
export const RESET_LOOP_DISPLAY_INDEX_FOR_CHILD = 'RESET_LOOP_DISPLAY_INDEX_FOR_CHILD';
export const SET_TASK_ANALYZED_COMMANDS = 'SET_TASK_ANALYZED_COMMANDS';
export const SET_SHOW_ONLY_WITH_ERRORS = 'SET_SHOW_ONLY_WITH_ERRORS';
