{{- if .Values.ingress.enabled -}}
  {{- $fullName := include "frontend.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "frontend.fullname" . }}-master
  labels:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    helm.sh/chart: {{ include "frontend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: master
    ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/issuer: letsencrypt-prod
  {{- if (and (not (empty .Values.ingress.host)) (not (empty .Values.ingress.secretName))) }}
ingress.kubernetes.io/ssl-redirect: "true"
  {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
  {{- if .Values.ingress.tls }}
tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.secretName }}
  {{- end }}
  {{- end }}