export const FETCH_TASKS = 'FETCH_TASKS';
export const LOAD_MORE_TASKS = 'LOAD_MORE_TASKS';
export const STOP_PIPELINE_TASK = 'STOP_PIPELINE_TASK';
export const TASK_CHANGED = 'TASK_CHANGED';
export const UPDATE_NEW_PARSED_ROWS_COUNT = 'UPDATE_NEW_PARSED_ROWS_COUNT';
export const UPDATE_CURRENT_EXECUTE_COMMAND = 'UPDATE_CURRENT_EXECUTE_COMMAND';
