export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_COMMANDS_INFORMATION = 'FETCH_TASK_COMMANDS_INFORMATION';
export const FETCH_TASK_DATA = 'FETCH_TASK_DATA';
export const TASK_CHANGED_FROM_WS = 'TASK_CHANGED_FROM_WS';
export const TASK_STOP = 'TASK_STOP';
export const TASK_UPDATE_CURRENT_EXECUTE_COMMAND_FROM_WS = 'TASK_UPDATE_CURRENT_EXECUTE_COMMAND_FROM_WS';
