export const TASK = 'TASK';
export const TASK_COMMANDS_INFORMATION_LOADING = 'TASK_COMMANDS_INFORMATION_LOADING';
export const TASK_COMMANDS_INFORMATION = 'TASK_COMMANDS_INFORMATION';
export const TASK_DATA = 'TASK_DATA';
