export const SET_TASK = 'SET_TASK';
export const CLEAR_TASK = 'CLEAR_TASK';
export const SET_TASK_LOADING = 'SET_TASK_LOADING';
export const SET_TASK_COMMANDS_INFORMATION_LOADING = 'SET_TASK_COMMANDS_INFORMATION_LOADING';
export const SET_TASK_COMMANDS_INFORMATION = 'SET_TASK_COMMANDS_INFORMATION';
export const CLEAR_TASK_COMMANDS_INFORMATION = 'CLEAR_TASK_COMMANDS_INFORMATION';
export const SET_TASK_DATA = 'SET_TASK_DATA';
export const CLEAR_TASK_DATA = 'CLEAR_TASK_DATA';
