export const CLEAR_PIPELINE = 'CLEAR_PIPELINE';
export const FETCH_PIPELINE = 'FETCH_PIPELINE';
export const SAVE_PIPELINE = 'SAVE_PIPELINE';
export const RUN_PIPELINE = 'RUN_PIPELINE';
export const STOP_PIPELINE = 'STOP_PIPELINE';
export const CURRENT_PIPELINE_CHANGED = 'CURRENT_PIPELINE_CHANGED';
