export const CLEAR_PIPELINE = 'CLEAR_PIPELINE';
export const FETCH_PIPELINE = 'FETCH_PIPELINE';
export const FETCH_PIPELINE_LAST_DATA = 'FETCH_PIPELINE_LAST_DATA';
export const SAVE_PIPELINE = 'SAVE_PIPELINE';
export const RUN_PIPELINE = 'RUN_PIPELINE';
export const CURRENT_PIPELINE_CHANGED = 'CURRENT_PIPELINE_CHANGED';
export const INIT_DEFAULT_PIPELINE_PROPERTIES = 'INIT_DEFAULT_PIPELINE_PROPERTIES';
