export const SET_PIPELINE_LOADING = 'SET_PIPELINE_LOADING';
export const SET_PIPELINE = 'SET_PIPELINE';
export const SET_PIPELINE_ID = 'SET_PIPELINE_ID';
export const PIPELINE_CHANGE_ATTRIBUTE = 'PIPELINE_CHANGE_ATTRIBUTE';
