export const SET_PIPELINE_LOADING = 'SET_PIPELINE_LOADING';
export const SET_PIPELINE = 'SET_PIPELINE';
export const SET_PIPELINE_ID = 'SET_PIPELINE_ID';
export const SET_PIPELINE_STATUS = 'SET_PIPELINE_STATUS';
